version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: changeMe!
      MYSQL_DATABASE: myProjectDatabase
      MYSQL_USER: changeMe!
      MYSQL_PASSWORD: changeMe!
    ports:
      - '4306:3306'
    volumes:
      - db-data:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - 8080:80
      - 8443:443 #for https connections allowed by apache ssl configuration in default-ssl.conf
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - ./etc/ssl:/etc/ssl
      - ../:/var/www
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://changeMe!:changeMe!@database:3306/myProjectDatabase

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: changeMe!
      UPLOAD_LIMIT: 20M
    ports:
      - 8181:80

volumes:
  db-data: